### ISSUE TITLE
Pod is failing with v0.5.4

### ISSUE THREAD

**Issue by dkoshkin** [projectcalico/k8s-policy#91]
OS: Ubuntu 16.04
Vagrant Machine
Kuberntes: v1.6.0
Using hostnames from `/etc/hosts` because of #69

Same spec file works with `v0.5.2` but fails with the error below on `v0.5.4`

```
root@master001:/etc/kubernetes/specs# kubectl logs calico-policy-controller-2822225049-3hbhh -n kube-system
2017-04-14 15:22:18,187 5 INFO Configuring /etc/hosts
2017-04-14 15:22:18,188 5 INFO Appended 'kubernetes.default  -> 172.17.0.1' to /etc/hosts
2017-04-14 15:22:18,189 5 INFO Beginning execution
2017-04-14 15:22:18,189 5 INFO Leader election enabled? False
Traceback (most recent call last):
  File "<string>", line 545, in <module>
  File "<string>", line 146, in run
  File "site-packages/pycalico/datastore.py", line 901, in delete_policy_tier
  File "site-packages/etcd/client.py", line 610, in delete
  File "site-packages/etcd/client.py", line 820, in wrapper
  File "site-packages/etcd/client.py", line 890, in api_execute
  File "site-packages/urllib3/request.py", line 66, in request
  File "site-packages/urllib3/request.py", line 87, in request_encode_url
  File "site-packages/urllib3/poolmanager.py", line 244, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 594, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 350, in _make_request
  File "site-packages/urllib3/connectionpool.py", line 833, in _validate_conn
  File "site-packages/urllib3/connection.py", line 324, in connect
  File "site-packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
  File "site-packages/urllib3/contrib/pyopenssl.py", line 197, in get_subj_alt_name
  File "site-packages/urllib3/contrib/pyopenssl.py", line 153, in _dnsname_to_stdlib
  File "site-packages/urllib3/contrib/pyopenssl.py", line 151, in idna_encode
  File "site-packages/idna/core.py", line 350, in encode
idna.core.IDNAError: Empty domain
controller returned -1
```

K8s spec file
```
root@master001:/etc/kubernetes/specs# cat policy-controller.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-policy-controller
  namespace: kube-system
  labels:
    tier: control-plane
    k8s-app: calico-policy-controller
  annotations:
    kismaticVersion: "1.3.1-beta.1-dirty"
spec:
  # The policy controller can only have a single active instance.
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-policy-controller
      namespace: kube-system
      labels:
        tier: control-plane
        k8s-app: calico-policy-controller
        kismaticVersion: "1.3.1-beta.1-dirty"
    spec:
      # The policy controller must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      volumes:
        # Mount in the etcd TLS secrets.
        - name: etcd-certs
        - name: "ca"
          hostPath:
            path: "/etc/kubernetes/ca.pem"
        - name: "cert"
          hostPath:
            path: "/etc/kubernetes/kubenode.pem"
        - name: "key"
          hostPath:
            path: "/etc/kubernetes/kubenode-key.pem"
      containers:
        - name: calico-policy-controller
          image: calico/kube-policy-controller:v0.5.4
          volumeMounts:
            - mountPath: "/etc/kubernetes/ca.pem"
              name: "ca"
            - mountPath: "/etc/kubernetes/kubenode.pem"
              name: "cert"
            - mountPath: "/etc/kubernetes/kubenode-key.pem"
              name: "key"
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # The location of the Kubernetes API.  Use the default Kubernetes
            # service for API access.
            - name: K8S_API
              value: "https://master001:6443" # this can only be a hostname, use master 0 for now
            - name: CONFIGURE_ETC_HOSTS
              value: "true"
```

**Comment by tmjd** [comment]
I thought maybe we had picked up a bad version of idna and that maybe a new release would fix this but I think 0.5.4 has the latest version of idna (2.5).

**Comment by tomdee** [comment]
@dkoshkin Are you able to retest with 0.6.0?

**Comment by dkoshkin** [comment]
@tomdee just tested, all looks good! Feel free to close.

**Comment by hreidar** [comment]
Hi, I'm getting the same error after upgrading from kismatic1.3.2 to kismatic1.3.3.

Here is the error:
```
2017-06-02T15:52:17.317154788Z 2017-06-02 15:52:17,316 7 INFO Configuring /etc/hosts
2017-06-02T15:52:17.318115415Z 2017-06-02 15:52:17,317 7 INFO Appended 'kubernetes.default  -> 172.17.0.1' to /etc/hosts
2017-06-02T15:52:17.318142521Z 2017-06-02 15:52:17,317 7 INFO Beginning execution
2017-06-02T15:52:17.319288644Z 2017-06-02 15:52:17,318 7 INFO Leader election enabled? False
2017-06-02T15:52:17.348649154Z Traceback (most recent call last):
2017-06-02T15:52:17.348721247Z   File "<string>", line 562, in <module>
2017-06-02T15:52:17.349044126Z   File "<string>", line 159, in run
2017-06-02T15:52:17.349078054Z   File "site-packages/pycalico/datastore.py", line 901, in delete_policy_tier
2017-06-02T15:52:17.349098896Z   File "site-packages/etcd/client.py", line 610, in delete
2017-06-02T15:52:17.349115926Z   File "site-packages/etcd/client.py", line 820, in wrapper
2017-06-02T15:52:17.349131653Z   File "site-packages/etcd/client.py", line 890, in api_execute
2017-06-02T15:52:17.34914836Z   File "site-packages/urllib3/request.py", line 66, in request
2017-06-02T15:52:17.349775254Z   File "site-packages/urllib3/request.py", line 87, in request_encode_url
2017-06-02T15:52:17.349850291Z   File "site-packages/urllib3/poolmanager.py", line 244, in urlopen
2017-06-02T15:52:17.349861178Z   File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
2017-06-02T15:52:17.349868216Z   File "site-packages/urllib3/connectionpool.py", line 345, in _make_request
2017-06-02T15:52:17.349874438Z   File "site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
2017-06-02T15:52:17.349880838Z   File "site-packages/urllib3/connection.py", line 333, in connect
2017-06-02T15:52:17.349888876Z   File "site-packages/urllib3/contrib/pyopenssl.py", line 343, in getpeercert
2017-06-02T15:52:17.349913715Z   File "site-packages/urllib3/contrib/pyopenssl.py", line 219, in get_subj_alt_name
2017-06-02T15:52:17.349922442Z   File "site-packages/urllib3/contrib/pyopenssl.py", line 175, in _dnsname_to_stdlib
2017-06-02T15:52:17.349930818Z   File "site-packages/urllib3/contrib/pyopenssl.py", line 173, in idna_encode
2017-06-02T15:52:17.349943122Z   File "site-packages/idna/core.py", line 350, in encode
2017-06-02T15:52:17.349951503Z idna.core.IDNAError: Empty domain
2017-06-02T15:52:17.349959245Z controller returned -1
```
and here is my k8s specs:
```
root@kube-dev-master1:/etc/kubernetes/specs# cat policy-controller.yaml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-policy-controller
  namespace: kube-system
  labels:
    tier: control-plane
    k8s-app: calico-policy-controller
  annotations:
    kismatic/version: "1.3.3"
spec:
  # The policy controller can only have a single active instance.
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-policy-controller
      namespace: kube-system
      labels:
        tier: control-plane
        k8s-app: calico-policy-controller
    spec:
      # The policy controller must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      volumes:
        - name: "ca"
          hostPath:
            path: "/etc/kubernetes/ca.pem"
        - name: "cert"
          hostPath:
            path: "/etc/kubernetes/kubenode.pem"
        - name: "key"
          hostPath:
            path: "/etc/kubernetes/kubenode-key.pem"
      containers:
        - name: calico-policy-controller
          image: calico/kube-policy-controller:v0.6.0
          volumeMounts:
            - mountPath: "/etc/kubernetes/ca.pem"
              name: "ca"
            - mountPath: "/etc/kubernetes/kubenode.pem"
              name: "cert"
            - mountPath: "/etc/kubernetes/kubenode-key.pem"
              name: "key"
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # The location of the Kubernetes API.  Use the default Kubernetes
            # service for API access.
            - name: K8S_API
              value: "https://#.#.#.#:6443"
            - name: CONFIGURE_ETC_HOSTS
              value: "true"
root@kube-dev-master1:/etc/kubernetes/specs# 
```
Any idea what could be wrong?

**Comment by tmjd** [comment]
This has been fixed in a later version of the policy controller, which is in kismatic master (see https://github.com/apprenda/kismatic/blob/master/ansible/group_vars/all.yaml#L18).

As the error kind of indicates I think your certificate does not have a domain, you could try (if even possible) to add a domain name to your cert but that might cause other issues.

**Comment by hreidar** [comment]
@tmjd, I believe I'm running v0.6.0 and still seeing the error, is there something I'm missing?

**Comment by dkoshkin** [comment]
@hreidar please open an issue on the Kismatic repo and let's discuss there. Include the details of your environment.

**Comment by hreidar** [comment]
Will do.

**Comment by tmjd** [comment]
For anyone else following along here is the Kismatic issue. https://github.com/apprenda/kismatic/issues/569

**Comment by dkoshkin** [comment]
@tmjd I have some more detail on this. I was able to reproduce the issue @hreidar is seeing.

I have a cluster with poilcy-controller `v0.4.0` with no policies and with conf file:
```
root@master001:/etc/cni/net.d# cat 10-calico.conf
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_endpoints": "https://etcd001:6666",
		"etcd_key_file": "/etc/kubernetes/kubenode-key.pem",
    "etcd_cert_file": "/etc/kubernetes/kubenode.pem",
    "etcd_ca_cert_file": "/etc/kubernetes/ca.pem",
    "hostname": "master001",
    "ipam": {
      "type": "calico-ipam"
    },
    "log_level": "info",
    "policy": {
      "type": "k8s"
    },
    "kubernetes": {
      "kubeconfig": "/var/lib/kubelet/kubeconfig"
    }
}
```
kubeconfig:
```
root@master001:/etc/cni/net.d# cat /var/lib/kubelet/kubeconfig
apiVersion: v1
kind: Config
clusters:
- name: kubernetes
  cluster:
    certificate-authority: /etc/kubernetes/pki/ca.pem
    server: "https://192.168.42.3:6443"
users:
- name: admin
  user:
    username: admin
    password: "WoFqiNircimambozu"
contexts:
- name: kubernetes
  context:
    cluster: kubernetes
    user: admin
current-context: kubernetes
```

After following the upgrade instructions of scaling down the pod and deploying the new version `v0.6.0` we switched to having calico deployment write out the conf file and now it looks like:
```
root@master001:/etc/cni/net.d# cat 10-calico.conf
{
    "name": "k8s-pod-network",
    "type": "calico",
    "etcd_endpoints": "https://etcd001:6666",
    "etcd_key_file": "/etc/kubernetes/pki/etcd-client-key.pem",
    "etcd_cert_file": "/etc/kubernetes/pki/etcd-client.pem",
    "etcd_ca_cert_file": "/etc/kubernetes/pki/ca.pem",
    "ipam": {
        "type": "calico-ipam"
    },
    "log_level": "info",
    "policy": {
        "type": "k8s",
        "k8s_api_root": "https://172.17.0.1:443",
        "k8s_auth_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLWYxZGZtIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIzYmNjYjY1ZC01MTBmLTExZTctYjQ3MS0wODAwMjdjMzBhODUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.kS5uwwFDtohY_r5Asc7YrfwlIcoMnn-3HJV9Vt1dqWdOkHEsE60tDrUTeOazhHb-j74CLFQ3OmVCha58ClYctcsSG6Rh5b1YUboMKOdl6deKrfi7umH59LOPhBrftNDvg-mtAo7Pn0za2IEioz79pAbXOf6DVlDKZVcYY0rlWaK4i8C5j0TaaV1VrIr49pQppdL5rBZc39JhsEfi-d8_jROhlLcHrdExx31HkZPgslg568mSShbhZswlYAvs4LGCt-PAladbiWYbE08bHbOxWNAzgAmF7dHCKNroQJvylSdDG9nqf33tvQz6v4wk1upZ-AT_c5fbX9HSXxzwJqD1tQ"
    },
    "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
    }
}
```
calico-kubeconfig:
```
root@master001:/etc/cni/net.d# cat calico-kubeconfig
# Kubeconfig file for Calico CNI plugin.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    insecure-skip-tls-verify: true
users:
- name: calico
contexts:
- name: calico-context
  context:
    cluster: local
    user: calico
current-context: calico-context
```

The logs in the pod:
```
➜  out git:(network-policy-upgrade) ✗ kubectl logs calico-policy-controller-3124103607-lsjgh -n kube-system
2017-06-14 15:11:29,733 5 INFO Configuring /etc/hosts
2017-06-14 15:11:29,733 5 INFO Appended 'kubernetes.default  -> 172.17.0.1' to /etc/hosts
2017-06-14 15:11:29,734 5 INFO Beginning execution
2017-06-14 15:11:29,734 5 INFO Leader election enabled? False
Traceback (most recent call last):
  File "<string>", line 562, in <module>
  File "<string>", line 159, in run
  File "site-packages/pycalico/datastore.py", line 901, in delete_policy_tier
  File "site-packages/etcd/client.py", line 610, in delete
  File "site-packages/etcd/client.py", line 820, in wrapper
  File "site-packages/etcd/client.py", line 890, in api_execute
  File "site-packages/urllib3/request.py", line 66, in request
  File "site-packages/urllib3/request.py", line 87, in request_encode_url
  File "site-packages/urllib3/poolmanager.py", line 244, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 345, in _make_request
  File "site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
  File "site-packages/urllib3/connection.py", line 333, in connect
  File "site-packages/urllib3/contrib/pyopenssl.py", line 343, in getpeercert
  File "site-packages/urllib3/contrib/pyopenssl.py", line 219, in get_subj_alt_name
  File "site-packages/urllib3/contrib/pyopenssl.py", line 175, in _dnsname_to_stdlib
  File "site-packages/urllib3/contrib/pyopenssl.py", line 173, in idna_encode
  File "site-packages/idna/core.py", line 350, in encode
idna.core.IDNAError: Empty domain
controller returned -1
```

I did try to deploy the old `v0.4.0` with the new config and then upgrade it to `v0.6.0` and that worked so it looks like the change in the config file breaks something. Not sure if its possible to clean up the old etcd data.

**Comment by tmjd** [comment]
@caseydavenport You've got a lot more history and knowledge here, can you shed any light on this issue?

The 10-calico.conf and calico-kubeconfig are only utilized by the CNI plugins,  the calico-policy-controller does not read them.  Looking at the policy-controller.yaml @hreidar included shows ca, cert, and keys being mounted into the policy-controller.  That is not the standard location as far as I'm aware of for those items (maybe they once were), but I think the ca would need to be at `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` according to https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/ and they should be added automatically by k8s.  Why are those mounts needed?

**Comment by caseydavenport** [comment]
Just catching up on this one.

> The 10-calico.conf and calico-kubeconfig are only utilized by the CNI plugins

Yep, that's correct - changes to those files shouldn't impact the policy controller.

```
          volumeMounts:
            - mountPath: "/etc/kubernetes/ca.pem"
              name: "ca"
            - mountPath: "/etc/kubernetes/kubenode.pem"
              name: "cert"
            - mountPath: "/etc/kubernetes/kubenode-key.pem"
              name: "key"
```

I'm also wondering why those mounts are needed - typically for communication with the apiserver the service account token and ca.crt are mounted into the container by the kubelet already, and the policy controller will use those by default.

```
  File "site-packages/pycalico/datastore.py", line 901, in delete_policy_tier
```

^ If it helps, the traceback appears to indicate that the error is occurring when the policy controller tries to access etcd, rather than when it's accessing the apiserver.

@dkoshkin I noticed your two configs are using different locations for the etcd certificates -

`"etcd_key_file": "/etc/kubernetes/kubenode-key.pem",` vs `"etcd_key_file": "/etc/kubernetes/pki/etcd-client-key.pem",` - wanted to double check that those are correct, and that you're not mixing up certs for the kubelet vs certs for Calico's etcd.

**Comment by dkoshkin** [comment]
Yeah those are correct, I should also add that a clean installation works fine with the same spec/version.
I only see the error when an the old policy has been running in the cluster.

**Comment by caseydavenport** [comment]
Interesting.  I wonder what could be different about upgrading that would cause this.

My hunch was that there's something odd about the SANs in the certificate, given the failure we're seeing is [in this code](https://github.com/shazow/urllib3/blob/1.20/urllib3/contrib/pyopenssl.py#L181), but it would seem odd that the code works fine if installed fresh but breaks on upgrade (assuming the certs are the same in both cases).

**Comment by tmjd** [comment]
@dkoshkin Is there anyway you could generate the certificates for etcd, both the etcd server certificates and the ones used by calico to access etcd and the CA and attach those here from the broken setup?  I would like to take those and do my own setup for some testing, I am with Casey that I think the secret is in the certs.

From my read of the code and the backtrace, the issue is with the certificate that is returned from the peer (`get_peer_certificate`).  Which I would interpret as the cert that etcd is presenting.
Would there be any chance to bring up a v0.4.0 setup and then only update the policy controller to v0.6.0?

**Comment by dkoshkin** [comment]
[keys.zip](https://github.com/projectcalico/k8s-policy/files/1112906/keys.zip)

`etcd001.pem` and `etcd001-key.pem` are the keys used during the initial install.
`etcd001-etcd.pem` and `etcd001-etcd-key.pem` are the server certs.
`etcd-client.pem` and `etcd-client-key.pem` are the client certs that calico uses. 
`ca.pem` is the CA used to sign all these certs.

In both cases I have `"etcd_endpoints": "https://etcd001:6666",` in the conf file

**Comment by dkoshkin** [comment]
Just tried only upgrading the policy-controller version while keeping everything else the same, (certs, k8s components) from original install and getting the same error as above.

**Comment by tmjd** [comment]
Thank you for checking that out.  That's what I expected, but that verifies it isn't some other change but the mix of those keys and the policy-controller.

I haven't been able to try out anything yet with the keys you provided but will report back when I can.

**Comment by tmjd** [comment]
I couldn't do a setup like I was imagining because the ca.pem was not present in the zip file but I took a look at the etcd001.pem.  When I do `openssl x509 -in etcd001.pem -text -noout`, there is an entry that is `DNS:,`, so there is an "Empty Domain" as is reported with `idna.core.IDNAError: Empty domain` message.

Do you expect that should be valid? I looked through RFC 3280 https://www.ietf.org/rfc/rfc3280.txt and did not find explicit rules that a DNS in SANs could not be empty but did find that CA's must verify all the entries in the SANs and I don't believe a blank one would valid.  There is also this statement 
```
In addition, while the string " " is a legal domain name, subjectAltName
extensions with a dNSName of " " MUST NOT be used.
```

I believe this was probably a silently ignored error or possibly generated a warning previously but now is obviously not allowed.

**Comment by dkoshkin** [comment]
I have attached two zips, `archive` has the CA and was installed the same way as above which resulted in an empty DNS entry. `arvhice-v2` uses a different environment and does not have the empty DNS.

Upgrading failed in the first setup but succeeded on the second install with `archive-v2`, the policy pod is running.

It looks there an issue when moving from a cert that had the and DNS to a new cert missing that entry.

[Archive.zip](https://github.com/projectcalico/k8s-policy/files/1125978/Archive.zip)
[Archive-v2.zip](https://github.com/projectcalico/k8s-policy/files/1125979/Archive-v2.zip)

**Comment by dkoshkin** [comment]
Also want to add that `etcd001.pem` are the certs used initially during the install, they get replaced by `etcd001-etcd.pem` during the upgrade. 
`etcd001.pem` is the one with an empty DNS entry, `etcd001-etcd.pem` does not have that.

**Comment by tmjd** [comment]
I'm a little bit confused.  Do you still think the problem lies in the calico-policy-controller?
It kind of sounds like maybe etcd isn't picking up the new certificate during the upgrade.
